version: '3.9'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=password
      - MONGODB_SERVER=mongodb
      - MONGODB_PORT=27017
    volumes:
      # overriding src and node_modules to update app in container without rebuild
      - "./src:/app/src:ro"
      - "./node_modules:/app/node_modules"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongodb-data:
    driver: local

